#!/bin/bash

# 读取目录中所有文件的=号后面的值，并将结果输出到指定文件
# 假设目录名为dir，结果文件名为output.txt

# 遍历目录中的所有文件
for file in dir/*
do
  # 读取文件中所有=号后面的值
  values=$(grep -oE '=[^[:space:]]+' "$file")

  # 遍历每个值
  for value in $values
  do
    # 去掉=号
    value=${value:1}

    # 在这里处理每个值
    # 如果值是一个IP地址，您可以使用如下命令验证：
    # if [[ $value =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
    #   echo "$value is a valid IP address"
    # else
    #   echo "$value is not a valid IP address"
    # fi

    # 将值追加到结果文件中
    echo "$value" >> output.txt
  done
done


# 去掉两端的双引号
value=${value//\"/}

# 去掉字符串中所有的双引号
value=${value//\"/}
